application: twix-mit
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1d"

handlers:

- url: /newsme/digestreport/.*
  script: newmedigester.app

- url: /tasks/newsmedigestion/.*
  script: newmedigester.app
  login: admin
  
- url: /tasks/newsmedigestiondelete/.*
  script: newmedigester.app
  login: admin
  
- url: /tasks/newsmedigestionaddseed/.*
  script: newmedigester.app
  login: admin

- url: /favicon\.ico
  static_files: static/noun_project_296_1.png
  upload: static/noun_project_296_1.png
  
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /google8ee943bd0e7a999b\.html
  static_files: static/google8ee943bd0e7a999b.html
  upload: static/google8ee943bd0e7a999b.html

- url: /static
  static_dir: static
  expiration: "1d"
  
- url: /sitemap\.xml
  script: newmedigester.app

- url: .*
  script: newmedigester.app
  
inbound_services:
- warmup

error_handlers:
  - file: default_error.html
