application: twix-mit
version: 1
runtime: python
api_version: 1

default_expiration: "1d"

handlers:
- url: /tasks/dailymix/.*
  script: dailymix.py
  login: admin
  secure: optional

- url: /favicon\.ico
  static_files: static/noun_project_296_1.png
  upload: static/noun_project_296_1.png
  
- url: /static
  static_dir: static
  expiration: "1d"

- url: .*
  script: main.py
  secure: optional

# - url: /.*
#    static_files: static/default_error.html
#    upload: static/default_error.html
  
inbound_services:
- warmup

error_handlers:
  - file: default_error.html
