application: twix-mit
version: 1
runtime: python
api_version: 1

default_expiration: "1d"

handlers:

- url: /newsme/digestreport/.*
  script: newmedigester.py

- url: /tasks/newsmedigestion/.*
  script: newmedigester.py
  login: admin
  
- url: /tasks/newsmedigestiondelete/.*
  script: newmedigester.py
  login: admin
  
#- url: /tasks/dailymix/.*
#  script: dailymix.py
#  login: admin
#  secure: always

- url: /favicon\.ico
  static_files: static/noun_project_296_1.png
  upload: static/noun_project_296_1.png
  
- url: /static
  static_dir: static
  expiration: "1d"

- url: .*
  script: newmedigester.py

# - url: /.*
#    static_files: static/default_error.html
#    upload: static/default_error.html
  
inbound_services:
- warmup

error_handlers:
  - file: default_error.html
